In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#read the inputs values
dataset=pd.read_csv('CKD.csv')
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
#converting categorical data to numerical data
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
#see the dataset is Balanced or imbalanced with help of value_counts function
dataset['classification_yes'].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [5]:
#give all colunms name
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [6]:
#split the input and output datas
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
#standardize the value using StandardScaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
#create a model decisiontreeclasssifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini','entropy','log_loss'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 
grid = GridSearchCV(DecisionTreeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')    
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Anconda\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Anconda\lib\site-packages\sklearn\model_selection\_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Anconda\lib\site-packages\sklearn\tree\_classes.py", line 937, in fit
    super().fit(
  File "C:\Anconda\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Anconda\lib\site-packages\sklearn\model_selection\_search.py:969: UserWarning: One or more of the test scores are non-finite: [0.92905052 0.98859441 0.94327004 0.96250042 0.95470953 0.94754992
 0.92540478 0.9699497  0.96596973 0.94796098 0.94733214 0.95101974
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [10]:
# print best parameter after tuning 
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
print('the confusion matrix is \n',cm)
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print('the classification_Report is \n',clf_report)

the confusion matrix is
 [[50  1]
 [ 1 81]]
the classification_Report is
               precision    recall  f1-score   support

           0       0.98      0.98      0.98        51
           1       0.99      0.99      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.98      0.98       133
weighted avg       0.98      0.98      0.98       133

In [11]:
#Calculate the F1Score 
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'splitter': 'random'}: 0.9849624060150376

In [12]:
#calculate the roc_auc_score 
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9840985174557627

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.004605,0.005641,0.000000,0.000000,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",0.945100,0.869709,0.943651,0.924528,0.962264,0.929051,0.031987,11
1,0.003129,0.006257,0.000000,0.000000,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",1.000000,0.961755,1.000000,1.000000,0.981217,0.988594,0.015265,1
2,0.000432,0.000865,0.006529,0.005665,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.922185,0.925524,0.943093,0.962264,0.943270,0.017440,10
3,0.005633,0.006969,0.002926,0.004354,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.963284,0.943041,0.925146,0.981031,1.000000,0.962500,0.026549,4
4,0.004583,0.004244,0.001648,0.003297,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.963284,0.961755,0.925146,0.942332,0.981031,0.954710,0.019200,5
5,0.005961,0.005416,0.003535,0.006111,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.945100,0.923510,0.981217,0.906705,0.981217,0.947550,0.030064,8
6,0.008628,0.007226,0.000000,0.000000,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.908877,0.888646,0.944023,0.923652,0.961826,0.925405,0.025693,12
7,0.009379,0.007658,0.000000,0.000000,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.981569,1.000000,0.962264,0.943651,0.962264,0.969950,0.019224,2
8,0.000000,0.000000,0.006250,0.007655,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.981569,0.943699,0.981217,0.942332,0.981031,0.965970,0.018748,3
9,0.009446,0.005948,0.002409,0.002951,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.889851,0.962636,0.944023,0.981031,0.962264,0.947961,0.031324,7
10,0.000000,0.000000,0.003129,0.006257,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.981569,0.923510,0.888286,0.962264,0.981031,0.947332,0.036290,9
11,0.006257,0.007664,0.000000,0.000000,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.945100,0.922185,0.944023,0.981217,0.962573,0.951020,0.019803,6
12,0.000640,0.001281,0.000000,0.000000,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.000000,0.000000,0.000000,0.000000,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
14,0.002225,0.002994,0.000000,0.000000,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
15,0.005548,0.005803,0.000000,0.000000,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
16,0.006258,0.007665,0.000000,0.000000,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.003125,0.006250,0.000000,0.000000,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,18

In [22]:
#input from user
age_input=int(input("Age:"))
bp_input=int(input("bp:"))
su_input=int(input("su:"))
bgr_input=int(input("bgr:"))
bu_input=int(input("bu:"))
sc_input=int(input("sc:"))
sod_input=int(input("sod:"))
pot_input=int(input("pot:"))
hrmo_input=int(input("hrmo:"))
pcv_input=int(input("pcv:"))
wc_input=int(input("wc:"))
rc_input=int(input("rc':"))
sg_b_input=int(input("sg_b:"))
sg_c_input=int(input("sg_c:"))
sg_d_input=int(input("sg_d:"))
sg_e_input=int(input("sg_e:"))
rbc_normal_input=int(input("rbc_normal:"))
pc_normal_input=int(input("pc_normal:"))
pcc_present_input=int(input("pcc_present:"))
ba_present_input=int(input("ba_present:"))
htn_yes_input=int(input("htn_yes:"))
dm_yes_input=int(input("dm_yes:"))
cad_yes_input=int(input("cad_yes:"))
appet_yes_input=int(input("appet_yes:"))
pe_yes_input=int(input("pe_yes:"))
ane_yes_input=int(input("ane_yes:"))

Age:52
bp:80
su:120
bgr:74
bu:25
sc:64
sod:45
pot:57
hrmo:56
pcv:21
wc:45
rc':64
sg_b:67
sg_c:80
sg_d:91
sg_e:1240
rbc_normal:3
pc_normal:1
pcc_present:0
ba_present:1
htn_yes:1
dm_yes:1
cad_yes:1
appet_yes:1
pe_yes:1
ane_yes:1

In [23]:
Classification_Prediction=grid.predict([[age_input,bp_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,
                                   hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,
                                   rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,
                                   dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input,age_input]])

print("Classification_Prediction={}".format(Classification_Prediction))

Classification_Prediction=[1]