In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#read the inputs values
dataset=pd.read_csv('CKD.csv')
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [3]:
#converting categorical data to numerical data
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [4]:
#give all colunms name
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [5]:
#split the input and output datas
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset[['classification_yes']]

In [6]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [7]:
#standardize the value using StandardScaler
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [8]:
#model creation of KNeighborsClassifiers
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'n_neighbors':[7,10],'weights':['uniform','distance'],'algorithm':['auto','ball_tree','kd_tree','brute'],
              'metric':['minkowski'],'p':[2]} 
grid = GridSearchCV(KNeighborsClassifier(), param_grid,refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted') 
# fitting the model for grid search 
grid.fit(X_train, y_train)

Fitting 5 folds for each of 16 candidates, totalling 80 fits

C:\Anconda\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)

GridSearchCV(estimator=KNeighborsClassifier(), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'metric': ['minkowski'], 'n_neighbors': [7, 10],
                         'p': [2], 'weights': ['uniform', 'distance']},
             scoring='f1_weighted', verbose=3)

In [9]:
# print best parameter after tuning 
re=grid.cv_results_
grid_predictions = grid.predict(X_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)
# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)
print('the confusion metrix is \n',cm)
print('the classification report is \n',clf_report)

the confusion metrix is
 [[51  0]
 [ 8 74]]
the classification report is
               precision    recall  f1-score   support

           0       0.86      1.00      0.93        51
           1       1.00      0.90      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.95      0.94       133
weighted avg       0.95      0.94      0.94       133

C:\Anconda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)

In [10]:
#Calculate the F1Score 
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'algorithm': 'auto', 'metric': 'minkowski', 'n_neighbors': 7, 'p': 2, 'weights': 'uniform'}: 0.9404945931261721

In [12]:
#calculate the roc_auc_score 
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9996413199426112

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_metric,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.017485,0.017306,0.016655,0.002372,auto,minkowski,7,2,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
1,0.007385,0.002925,0.012544,0.002378,auto,minkowski,7,2,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
2,0.008314,0.007514,0.011120,0.003329,auto,minkowski,10,2,uniform,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,13
3,0.008485,0.002947,0.003109,0.001304,auto,minkowski,10,2,distance,"{'algorithm': 'auto', 'metric': 'minkowski', '...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
4,0.012547,0.004342,0.008645,0.001411,ball_tree,minkowski,7,2,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
5,0.006591,0.001019,0.003384,0.000988,ball_tree,minkowski,7,2,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
6,0.006520,0.001629,0.009651,0.001836,ball_tree,minkowski,10,2,uniform,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,13
7,0.008124,0.001668,0.004937,0.001665,ball_tree,minkowski,10,2,distance,"{'algorithm': 'ball_tree', 'metric': 'minkowsk...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
8,0.007109,0.000704,0.012163,0.003424,kd_tree,minkowski,7,2,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
9,0.009108,0.003947,0.002558,0.005115,kd_tree,minkowski,7,2,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
10,0.006784,0.007581,0.009619,0.007854,kd_tree,minkowski,10,2,uniform,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,13
11,0.008412,0.006868,0.004658,0.003803,kd_tree,minkowski,10,2,distance,"{'algorithm': 'kd_tree', 'metric': 'minkowski'...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
12,0.007030,0.001496,0.006533,0.003199,brute,minkowski,7,2,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
13,0.002495,0.002518,0.002603,0.005205,brute,minkowski,7,2,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1
14,0.007808,0.006375,0.005205,0.006375,brute,minkowski,10,2,uniform,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.854321,0.925764,0.907035,0.981217,0.962573,0.926182,0.044461,13
15,0.002603,0.005205,0.003129,0.006258,brute,minkowski,10,2,distance,"{'algorithm': 'brute', 'metric': 'minkowski', ...",0.908877,0.944161,0.925524,0.981217,0.962573,0.944470,0.025706,1

In [14]:
#input from user
age_input=int(input("Age:"))
bp_input=int(input("bp:"))
su_input=int(input("su:"))
bgr_input=int(input("bgr:"))
bu_input=int(input("bu:"))
sc_input=int(input("sc:"))
sod_input=int(input("sod:"))
pot_input=int(input("pot:"))
hrmo_input=int(input("hrmo:"))
pcv_input=int(input("pcv:"))
wc_input=int(input("wc:"))
rc_input=int(input("rc':"))
sg_b_input=int(input("sg_b:"))
sg_c_input=int(input("sg_c:"))
sg_d_input=int(input("sg_d:"))
sg_e_input=int(input("sg_e:"))
rbc_normal_input=int(input("rbc_normal:"))
pc_normal_input=int(input("pc_normal:"))
pcc_present_input=int(input("pcc_present:"))
ba_present_input=int(input("ba_present:"))
htn_yes_input=int(input("htn_yes:"))
dm_yes_input=int(input("dm_yes:"))
cad_yes_input=int(input("cad_yes:"))
appet_yes_input=int(input("appet_yes:"))
pe_yes_input=int(input("pe_yes:"))
ane_yes_input=int(input("ane_yes:"))

Age:85
bp:70
su:90
bgr:78
bu:94
sc:25
sod:67
pot:85
hrmo:29
pcv:4
wc:125
rc':253
sg_b:25
sg_c:44
sg_d:55
sg_e:68
rbc_normal:85
pc_normal:25
pcc_present:45
ba_present:54
htn_yes:65
dm_yes:0
cad_yes:0
appet_yes:0
pe_yes:1
ane_yes:0

In [15]:
Classification_Prediction=grid.predict([[age_input,bp_input,su_input,bgr_input,bu_input,sc_input,sod_input,pot_input,
                                   hrmo_input,pcv_input,wc_input,rc_input,sg_b_input,sg_c_input,sg_d_input,sg_e_input,
                                   rbc_normal_input,pc_normal_input,pcc_present_input,ba_present_input,htn_yes_input,
                                   dm_yes_input,cad_yes_input,appet_yes_input,pe_yes_input,ane_yes_input,age_input]])

print("Classification_Prediction={}".format(Classification_Prediction))

Classification_Prediction=[1]

C:\Anconda\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)